repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        name: ruff linter check
        entry: uv run ruff check
        language_version: python3.14
        args: [--fix, .]
      - id: ruff-format
        name: ruff formatter
        language_version: python3.14
        entry: uv run ruff format
        args: [.]

  - repo: local
    hooks:
      - id: mypy
        name: mypy type checker
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: true
        args: [--config-file=pyproject.toml, .]
